version: '3.7'
services:
  db:
    hostname: jimi_db
    container_name: jimi_db
    image: mongo:latest
    volumes:
    #- ./jimi-db/data/db:/data/db
      - jimi_db_volume:/data/db
    ports:
    - "27017:27017"
    networks:
      jimi_net_bridge:
        #ipv4_address: 172.16.10.12


  core:
    hostname: jimi_core
    container_name: jimi_core
    depends_on: 
      - db
    hostname: jimi_core
    build:
      context: .
      dockerfile: ./docker/jimi-core/Dockerfile
    volumes:
    - ./jimi-core/data/log:/home/jimi/log
    - ./plugins:/home/jimi/plugins
    ports:
    - "5000:5000"
    tty: true
    entrypoint:  ["./entrypoint.sh"]
    networks:
      jimi_net_bridge:

  web:
    build:
      context: .
      dockerfile: ./docker/jimi-web/Dockerfile
    volumes:
    - ./jimi-web/data/log:/home/jimi/log
    - ./plugins:/home/jimi/plugins
    ports:
    - "4443:4443"
    - "5002:5002"
    networks:
      jimi_net_bridge:
    hostname: jimi_web
    container_name: jimi_web
    depends_on: 
      - core
    entrypoint: ["./start_web.sh"]

networks:
  jimi_net_bridge:
    driver: bridge
    #ipam:
    #  config:
    #    - subnet: "172.16.10.0/24"

volumes:
  jimi_db_volume:
